version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: prosopon
      POSTGRES_USER: prosopon
      POSTGRES_PASSWORD: prosopon
    ports:
      - "5432:5432"
    volumes:
      - prosopon-db-data:/var/lib/postgresql/data

volumes:
  prosopon-db-data:
